### ISSUE TITLE
[New Request] Progress Bar

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite-Legacy-Archive/Krypton-Toolkit-Suite-Extended-NET-5.470#100]
https://www.codeproject.com/Articles/48419/A-simple-custom-progressbar

**Comment by PWagner1** [comment]
Use newer toolkit for this

**Comment by Smurf-IV** [comment]
https://github.com/Krypton-Suite/Standard-Toolkit/issues/910#issuecomment-1666945478
